create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table contact
(
    id   bigint generated by default as identity,
    firstname varchar(200),
    lastname varchar(200),
    email_address varchar(200),
    phone_number varchar(200),
    comment varchar(200),
    company_id bigint,
    mystatus varchar(200),
    created_time date,
    last_modified_time date,
    constraint pk_contact primary key (id)
);


insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');
